name: Content Impress
author: panaghia
category: Effects
tags: [animation, usability, accessibility, read]
demo: http://panaghia.it/2010/content-impress-a-web-content-highlight-class-for-mootools
current: 0.1
